quarkus.container-image.builder=podman
quarkus.container-image.registry=quay.io
quarkus.container-image.group=wael2000
quarkus.container-image.name=quarkus-hello-world
quarkus.container-image.tag=1.1
