quarkus.container-image.builder=podman
quarkus.container-image.registry=quay.io
quarkus.container-image.group=wael2000
quarkus.container-image.name=quarkus-hello-world
quarkus.container-image.tag=1.1

# PostgreSQL
quarkus.datasource.db-kind=postgresql
quarkus.hibernate-orm.database.generation=none
quarkus.flyway.migrate-at-start=true
